apiVersion: v1
kind: ConfigMap
metadata:
  name: cryptocurrency-exchange-config
  namespace: cryptocurrency-exchange
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,crypto-exchange,crypto-exchange.cryptocurrency-exchange.svc"
  DATABASE_HOST: "postgresql"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "exchange"
  TZ: "Asia/Tehran"
